name: Interoperability Testing
on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  run-multidim-interop:
    name: Run multidimensional interoperability tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Build docker image
        run: docker buildx build --load -t kotlin-libp2p-head -f test-plans/Dockerfile .
      - name: Run tests
        uses: libp2p/test-plans/.github/actions/run-interop-ping-test@master
        with:
          test-filter: kotlin-libp2p-head
          extra-versions: ${{ github.workspace }}/test-plans/ping-version.json
